---
title: "ESM206 Assignment 5"
author: "Teresa Fukuda"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Load packages and data

library(tidyverse)
library (stargazer)
library(reshape2)

grad_enroll <-read_csv("grad_enrollment.csv")
med_salary <-read_csv("median_salary_postdoc.csv")
phds <-read_csv("phds.csv")
salary_data <- read_csv("salary_data.csv")

```

```{r}
###############################################################
# 1) Male and female graduate enrollment (1967 - 2015)
###############################################################

# Creating a simplified data frame excluding non profit and for profit schools as well as irrelavent totals
grad_enroll_ftf <- grad_enroll %>% 
  select(Year, full_time_m, full_time_f, part_time_m, part_time_f)

#creating a linear model for male graduate enrollment
male_grad <- lm(grad_enroll$total_males ~ grad_enroll$Year)

summary(male_grad)
plot(male_grad)

#creating a linear model for female graduate enrollment
female_grad <- lm(grad_enroll$total_females ~ grad_enroll$Year)

summary(female_grad)
plot(female_grad)

#create a graph of the models
enroll_graph <- grad_enroll %>% 
  ggplot(aes(x = Year, y = total_males))+
  geom_point(aes(color = "total_males"))+
  geom_smooth(aes(x = Year, y = total_males),method = lm, se = TRUE, size = 0.5, color = "gray20") + #plots the linear model with a confidence interval (se)
  geom_point(aes(x = Year, y = total_females, color = "total_females")) +
  geom_smooth(aes(x = Year, y = total_females),method = lm, se = TRUE, size = 0.5, color = "gray20")+
  theme_classic() +
  theme(legend.title=element_blank()) +
  scale_color_manual(" ", breaks = c("total_males", "total_females"), values = c("total_males" = "blue", "total_females" = "pink"), labels=c("Males", "Females")) +
  labs(x = "\nYear", y = "Total Enrollment\n", title = "Male and Female Graduate Enrollment (1967-2015)\n") +
  scale_x_continuous(expand = c(0,0), limits = c(1967, 2015)) +
  theme(text = element_text(family = "Times New Roman")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 10))

enroll_graph
```

```{r}
###############################################################
# 2) Shifts in female PhD recipients by field (1985, 2000, and 2015)
###############################################################

# First creating a data frame with just the 5 fields in question and just the 3 years of interest.
phds_summary <- phds %>%
  select("year", "physci_f", "engineer_f", "ed_f", "humart_f") %>% 
  filter(year == "1985" | year == "2000" | year == "2015") %>% 
  select("physci_f", "engineer_f", "ed_f", "humart_f") # I realize this line of code is redundant, but just put it in for my own understanding of the order in which things occurred.
rownames(phds_summary) <- c("1985", "2000", "2015")

#maybe a chisquare tests for proportions of females in each field by year
phds_chi <- chisq.test(phds_summary)
phds_chi

phds_prop <- prop.table(as.matrix(phds_summary), 1)

phds_summary2 <- phds %>%
  select("year", "physci_f", "engineer_f", "ed_f", "humart_f") %>% 
  filter(year == "1985" | year == "2000" | year == "2015") 

phds_summary3<-melt(phds_summary2, id.vars = 'year')

phds_graph<- phds_summary3 %>% 
  ggplot(aes(fill = variable, y = value, x = year)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_x_continuous(breaks = c(1985, 2000, 2015)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic() +
  labs(x = "\nYear", y = "Proportion\n", title = "Proportion of Female PhD Recipients\n") +
  theme(text = element_text(family = "Times New Roman")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 10)) 


phds_graph

# p-value < 0.001 therefore there is a significant association between the year a degree was awarded and the number of PhDs awarded to women in that year (X^2 = 2073, *p* , 0.001)


```

```{r}
###############################################################
# 3) Male and female salaries for starting postdoctoral and other employment positions (2015)
###############################################################

#2 mann whitney u tests (one for median postdoc salary male vs female, one for median other employment male vs female)

#explore data for posdoc salaries
male_post_sal <- ggplot(med_salary, aes(x = postdoc_m)) +
  geom_histogram(binwidth = 5000, aes(color = "black"))
male_post_sal #not normally distributed

# Checking the qq plot for this distribution
male_post_qq <- ggplot(med_salary, aes(sample = postdoc_m)) +
  geom_qq()
male_post_qq
#Looking like it's potentially linear

female_post_sal <- ggplot(med_salary, aes(x = postdoc_f)) +
  geom_histogram(binwidth = 5000, aes(color = "black"))
female_post_sal #not normally distributed

# Checking the qq plot for this distribution
female_post_qq <- ggplot(med_salary, aes(sample = postdoc_f)) +
  geom_qq()
female_post_qq
# NOT looking linear

#want comparison of means so do Mann Whitney U
#H0: Ranks are equal
#HA: ranks are different
post_sal_test <- wilcox.test(med_salary$postdoc_f, med_salary$postdoc_m)
post_sal_test

med_sal_2<-melt(med_salary, id.vars = 'field')

post_sal_graph <- med_sal_2 %>%  
  filter(variable == "postdoc_m" | variable == "postdoc_f") %>% 
  ggplot(aes(x = field, y = value)) +
  geom_col(aes(fill = variable), position = "dodge") +
  scale_fill_manual(values = c("blue", "pink"), labels = c("Male", "Female")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8)) +
  theme(legend.title=element_blank())+
  labs(x = "\nField", y = "Median Salary\n", title = "Male and Female Median Postdoc Salaries 2015") +
  theme(text = element_text(family = "Times New Roman")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(axis.title = element_text(size = 12)) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(labels = function(x) lapply(strwrap(x, width = 10, simplify = FALSE), paste, collapse="\n"))

post_sal_graph

#explore data for employement salaries
male_employ_sal <- ggplot(med_salary, aes(x = employment_m)) +
  geom_histogram(binwidth = 15000)
male_employ_sal #maybe normally distributed?

female_employ_sal <- ggplot(med_salary, aes(x = employment_f)) +
  geom_histogram(binwidth = 15000)
female_employ_sal #maybe normally distributed?

employ_sal_test <- wilcox.test(med_salary$employment_f, med_salary$employment_m)
employ_sal_test

employ_sal_graph <- med_sal_2 %>%  
  filter(variable == "employment_m" | variable == "employment_f") %>% 
  ggplot(aes(x = field, y = value)) +
  geom_col(aes(fill = variable), position = "dodge") +
  scale_fill_manual(values = c("blue", "pink"), labels = c("Male", "Female")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8)) +
  theme(legend.title=element_blank())+
  labs(x = "\nField", y = "Median Salary\n", title = "Male and Female Median non Postdoc Salaries 2015") +
  theme(text = element_text(family = "Times New Roman")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(axis.title = element_text(size = 12)) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(labels = function(x) lapply(strwrap(x, width = 10, simplify = FALSE), paste, collapse="\n"))

employ_sal_graph
```

```{r}
###############################################################
# 4) Exploring academic salaries for professors in U.S. colleges
###############################################################

# Find a good multiple linear regression model with the output being salary, and the variables (some combination of) sex, discipline, rank, years of service, years since phd 

# Some data exploration 
#plot of salary by gender
salary_plot <- ggplot (salary_data, aes(x=sex, y=salary))+
  geom_point(aes(color=faculty.rank), alpha=0.6)
salary_plot

#plot of salary by faculty rank
facultyrank_plot <- ggplot (salary_data, aes(x=faculty.rank, y=salary))+
  geom_point(aes(color=sex))
facultyrank_plot

# well this doesn't seem to be saying much, not seeing any glaring trends here

# summary table looking at salary by sex and faculty position... interesting? maybe.
avg_salary_sex <- salary_data %>% 
  group_by(sex, faculty.rank) %>% 
  summarize(mean= mean(salary),
            count=n())
avg_salary_sex

# linear model with ALL possible variables

salary_lm1 <- lm (salary ~ sex+faculty.rank+discipline+yrs.since.phd+yrs.service, data=salary_data)

summary(salary_lm1)

# taking out yrs.since.phd, since it likely pretty much same as years.service; also makes no sense that the years of service would have a negative coefficient

salary_lm2 <- lm(salary ~ sex+faculty.rank+discipline+yrs.service, data=salary_data)

summary(salary_lm2)

# yrs.service still has a negative coefficient... this is not logical


# taking out faculty.rank (since rank is mostly just determined by how long they are there?)
salary_lm3 <- lm(salary ~ sex+yrs.since.phd+discipline+faculty.rank, data=salary_data)

summary(salary_lm3)

plot(salary_lm3)

```

